---
- name: Install golang
  include_role:
    name: gantsign.golang
  vars:
    golang_version: "{{ tusd_golang_version }}"

- name: Install git
  apt:
    pkg: 
      - git
      - gcc
    state: present

- name: stat {{ tusd__executable_path }}
  stat:
    path: "{{ tusd__executable_path }}"
  register: p

- name: Git checkout {{ tusd__go_package }}
  git:
    repo: 'https://{{ tusd__go_package }}.git'
    dest: "{{ tusd__src_path }}"

- name: go build
  command: /opt/go/{{ tusd_golang_version }}/bin/go build -o tusd cmd/tusd/main.go
  args:
    chdir: "{{ tusd__src_path }}"
  environment:
    GOPATH: "{{ tusd__go_path }}"
  when: p.stat.exists == false

- name: Template {{ tusd__systemd_unit_path }}
  template:
    src: tusd.service
    dest: "{{ tusd__systemd_unit_path }}"
  notify: restart tusd
  when: tusd_enable_service

- name: Enable tusd.service
  systemd:
    name: tusd.service
    enabled: true
  notify: restart tusd
  when: tusd_enable_service
